#:schema node_modules/wrangler/config-schema.json
name = "webuild"
pages_build_output_dir = ".vercel/output/static"

# You were missing this line:
compatibility_date = "2024-12-16"

# Keep this if you want broader Next.js support, 
# though your new code might work without it.
compatibility_flags = ["nodejs_compat"]
